### PR TITLE
Be Js_of_ocaml friendly

### PR DESCRIPTION
**Pull request by schutm**
This is a big CR, I understand. I tried to make ocaml-cuid more Js_of_ocaml friendly and adhere more closely to the outline on https://usecuid.org.

The following (big) changes were made:
  * Split into cuid-unix and cuid-jv for (old) unix and new Jv compilation units (this changes the interface/api as well)
  * Removed dependency on mirage
  * Use the Stdlib of ocaml (in stead of base)
  * Use integer arithmetic (to speed up calculations)
  - Increased the used timer resolution to include nano seconds (just like the orginal nodejs implementation)
  - Use Int64 arithmetic in timestamp calculation, because timestamps overflows javascript's 32-bit integer implementation.

### CODE REVIEW

**Comment by marcoonroad** [comment]
Sorry for being a bit late (GH notifications are a thing which really need to be improved).
I will approve now the workflows and review the changes later on the weekend.
Thank you by the PR and best regards.

**Comment by marcoonroad** [comment]
Hi @schutm,

Although I really like the idea of removing the `mirage` dependency, unhappily the stdlib's `Random` module is not cryptographically secure (I've made this library with some focus on cryptographic usage). I think that we can make the generic `Cuid` functor parametric/abstract over some `RNG` implementation, and still use the `mirage` for Unix while the JavaScript target could use the native browser `window.crypto` API.
Such JS' API is quite simple to use, as found in the files below:

- https://github.com/marcoonroad/spadille/blob/master/src/spadille/secret/browser.js
- https://github.com/marcoonroad/spadille/blob/master/src/spadille/utils/bytes.js
- https://github.com/marcoonroad/spadille/blob/master/__tests__/secret.js

But, to be honest, I don't know if it's feasible to convert these examples into an OCaml-to-JS code.
Any thoughts?

**Comment by schutm** [comment]
Sorry for the late reply. I'd never considered CUIDs to be cryptographically secure...

However I'll try to  make the generic `Cuid' functor parametric/abstract over the `RNG' implementation.

**Comment by schutm** [comment]
Mirage is used again for the unix version; the web-crypto (if available, with fallback to random) is used for the javascript version.

In addition I've changed the generate function as it wasn't given the entropy expected (in my opinion). Since e.g. 36 * 36 * 36 * 35 gave the same result as 35 * 36 * 36 * 36 and this should be different. So instead of a simple multiplication it is now a multiplication and a power to respect the position of the returned value.

**Comment by marcoonroad** [comment]
The build fails for versions prior 4.08 and on windows environment, I'll update the opam metadata and CI files to cover that.

**Comment by marcoonroad** [comment]
Thanks a lot by the contribution! 🎉

**Pull request merged**
